### PR TITLE
Add Niagara system and Planck NPIPE

### PR DESCRIPTION
**Pull request by msyriac**
Not adding Penn GPC for now.

### CODE REVIEW

**Comment by msyriac** [comment]
Note that for Planck NPIPE, the split numbers are 1 and 2, rather than 0 and 1.  And the map tags are slightly different. But sofind seems flexible enough not to care.

**Review by zatkins2 — APPROVED** [review]

**Comment by zatkins2** [comment]
This is all great, thanks for adding. 

For Planck, that is good to know. You're right that `sofind` won't care, but `mnms` will, because it does iteration over splits in couple places like `range(num_splits)`.

Could you also target `develop` for this PR?

**Comment by msyriac** [comment]
How do you go about addressing the split number filename mismatch? (I'll work on targeting to `develop`)

**Comment by zatkins2** [comment]
I don't really see a way around cluing `mnms` to expect some other iterable of splits. So somehow that information would need to be recorded explicitly (e.g., if not added, assume 0-indexed, otherwise, some item in a yaml that just lists out the split iterable). This would likely be an addition to these Planck yamls you just added, but let's worry about that when we know what we want.

**Pull request merged**
